DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS booking CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255)        NOT NULL,
    email        VARCHAR(512) UNIQUE NOT NULL,
    time_created TIMESTAMP           NOT NULL DEFAULT (CURRENT_TIMESTAMP())
);

CREATE TABLE IF NOT EXISTS item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR,
    description  VARCHAR,
    available    BOOLEAN   NOT NULL DEFAULT (false),
    user_id      BIGINT    NOT NULL REFERENCES users (id),
    time_created TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP())
);

CREATE TABLE IF NOT EXISTS booking
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id      BIGINT                      NOT NULL REFERENCES item (id),
    booker_id    BIGINT                      NOT NULL REFERENCES users (id),
    status       VARCHAR(60)                 NOT NULL,
    time_created TIMESTAMP                   NOT NULL DEFAULT (CURRENT_TIMESTAMP())
);

CREATE TABLE IF NOT EXISTS comments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text         VARCHAR   NOT NULL,
    item_id      BIGINT    NOT NULL REFERENCES item (id),
    author_id    BIGINT    NOT NULL REFERENCES users (id),
    time_created TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP())
);

